import { Inter, Playfair_Display } from "next/font/google";
import Footer from "./components/moleculs/Footer/page";
import Navigation from "./components/moleculs/Navbar/page";
import "./globals.css";
import { ThemeProvider } from "./components/atoms/ThemeProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata = {
  title: "DKM Ayatul Muthmainnah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id" className="scroll-smooth" suppressHydrationWarning>
      <body className={`${inter.variable} ${playfair.variable} font-sans`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navigation />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
